### ISSUE TITLE
Determine the purpose of your database 

### ISSUE THREAD

**Issue by Faithful1** [BuildForSDGCohort2/Confyde-Backend#1]
This should give us context as to what the database is for and the plan for its build. it should answer questions like:

1. Are we using Nosql vs sql
2. What database engine do you plan to use
3. Possibly a Schema already planned?

**Comment by binarygeotech** [comment]
We are using RDB (Relational DataBase) and MySQL to be precise.
We have planned the schema which is subjected to change as development progresses.

**Comment by Faithful1** [comment]
Since the expected deliverable for this is just a decision on database choice. I will close this issue
