### ISSUE TITLE
[chore] Project Initialization

### ISSUE THREAD

**Issue by binarygeotech** [BuildForSDGCohort2/Confyde-Backend#4]
### Project Initialization
The project will be a REST API service using NestJS and MySQL.

### Todo
- [x] Create Project
- [x] Push initial commit
- [x] Create project file/directory structures to match project layout

**Comment by Faithful1** [comment]
@binarygeotech  Just following up on the progress of this based on the Todo? Any update yet?

**Comment by Faithful1** [comment]
Deliverables for this has been completed as seen in the TODO 
So i will close this issue

**Comment by Faithful1** [comment]
will leave this open for now since it is still linked to an issue that is still in progress

**Comment by Faithful1** [comment]
i will close this issue as we have checked all todos
